### 상품 등록 (셀러)
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwUitpcTFsNTNwV2hQalFoT3F0UTFnPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6IlNFTExFUiIsImlhdCI6MTcxNjY0NDY4MCwiZXhwIjoxNzE2NzMxMDgwfQ.n0Wg5fLEhes5xKIp85T_lzu7NdYAMDDoBgUUPXwkFHM



{
  "addProductItemForms": [
    {
      "count": 3,
      "name": "에어포스 그린",
      "price": 1000
    },
    {
      "count": 3,
      "name": "에어포스 레드",
      "price": 1500
    },
    {
      "count": 2,
      "name": "에어포스 블루",
      "price": 1000
    }
  ],
  "description": "신발 입니다.",
  "name": "나이키 에어포스"
}

### 상품 항목(Product Item) 조회
GET http://localhost:8082/seller/product/item?id=1


### 상품 항목(Product Item) 등록 (셀러)
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwUitpcTFsNTNwV2hQalFoT3F0UTFnPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6IlNFTExFUiIsImlhdCI6MTcxNjU1MDA0OSwiZXhwIjoxNzE2NjM2NDQ5fQ.u9ZVAqb9VzPi5fhXtPHGN8Ln8UC5Ipz5ouqaVK69n4A


{
  "count": 1,
  "name": "에어포스 된장",
  "price": 5000,
  "productId": 1
}

### 상품 수정 (셀러)
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwUitpcTFsNTNwV2hQalFoT3F0UTFnPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6IlNFTExFUiIsImlhdCI6MTcxNjU1MDA0OSwiZXhwIjoxNzE2NjM2NDQ5fQ.u9ZVAqb9VzPi5fhXtPHGN8Ln8UC5Ipz5ouqaVK69n4A


{
  "description": "백팩 입니다.",
  "id": 1,
  "items": [
    {
      "count": 3,
      "id": 2,
      "name": "잔스포츠 마끼야또",
      "price": 1000,
      "productId": 1
    },
    {
      "count": 3,
      "id": 4,
      "name": "잔스포츠 돌체",
      "price": 1000,
      "productId": 1
    }
  ],
  "name": "잔스포츠",
  "productId": 1
}

### 상품 항목(Product Item) 수정 (셀러)
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwUitpcTFsNTNwV2hQalFoT3F0UTFnPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6IlNFTExFUiIsImlhdCI6MTcxNjU1MDA0OSwiZXhwIjoxNzE2NjM2NDQ5fQ.u9ZVAqb9VzPi5fhXtPHGN8Ln8UC5Ipz5ouqaVK69n4A


{
  "id": 1,
  "count": 1,
  "name": "잔스포츠 된장",
  "price": 5000,
  "productId": 1
}

### 상품 삭제 (셀러)
DELETE http://localhost:8082/seller/product?productId=2
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwUitpcTFsNTNwV2hQalFoT3F0UTFnPT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6IlNFTExFUiIsImlhdCI6MTcxNjU1MDA0OSwiZXhwIjoxNzE2NjM2NDQ5fQ.u9ZVAqb9VzPi5fhXtPHGN8Ln8UC5Ipz5ouqaVK69n4A


### 상품 검색
GET http://localhost:8082/search/product?name=나이키 에어포스
Content-Type: application/json

### 상품 상세 검색
GET http://localhost:8082/search/product/detail?productId=1
Content-Type: application/json